import type { Metadata } from "next";
import "antd/dist/reset.css";
import "./globals.css";
import { cn } from "@/lib/utils";
import AntdProvider from "@/components/providers/AntdProvider";

export const metadata: Metadata = {
  title: "oka voyages",
  description: "Generated by IFUMBA",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body suppressHydrationWarning className={cn("antialiased")}>
        <AntdProvider>{children}</AntdProvider>
      </body>
    </html>
  );
}
